name: codem_eval
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9.13
    - python-pdal
    - opencv
    - rasterio
    - trimesh
    - matplotlib
    - scikit-image
    - enlighten
    - numpy==1.20.3
    - typing-extensions
    - pdal==2.4.3
    - rich
    - ipykernel
    - pip
    - pip:
      - hydra-core
      - codem
